# We publish API docs any time we publish code to main.
name: api-docs - publish

on:
  push:
    branches:
      - main

jobs:

  publish:
    name: Publish API docs to S3 on changes to `main`
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: make build-docs

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
#          aws-region: us-east-1

#      - name: Sync API docs to S3
#        run: |
#          aws s3 cp api-docs/index.html s3://${{ secrets.S3_BUCKET }}/api-docs/ --sse --acl public-read
#          aws s3 cp api-docs/openapi.yml s3://${{ secrets.S3_BUCKET }}/api-docs/ --sse --acl public-read
